import { HomePage } from '@/components';
import HomePageContent from '@/staticPageData/HomePageContent';
import Head from 'next/head'
import styled from 'styled-components'

export default function Home() {
  return (
    <>
      <Head>
        <title>FundsDome</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />

        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Home | FundsDome</title>
        <link rel="apple-touch-icon" sizes="180x180" href="assets/images/favicons/apple-touch-icon.png" />
        <link rel="icon" type="image/png" sizes="32x32" href="assets/images/favicons/favicon-32x32.png" />
        <link rel="icon" type="image/png" sizes="16x16" href="assets/images/favicons/favicon-16x16.png" />
        <link rel="manifest" href="assets/images/favicons/site.webmanifest" />
        <meta name="description" content="FundsDome" />

        <link href="https://fonts.googleapis.com/css2?family=DM+Sans:opsz,wght@9..40,400;9..40,500;9..40,600;9..40,700&amp;display=swap" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css2?family=Quicksand:wght@500;600;700&amp;display=swap" rel="stylesheet" />


        <link rel="stylesheet" href="assets/vendors/bootstrap/css/bootstrap.min.css" />
        <link rel="stylesheet" href="assets/vendors/animate/animate.min.css" />
        <link rel="stylesheet" href="assets/vendors/fontawesome/css/all.min.css" />
        
        <link rel="stylesheet" href="assets/vendors/owl-carousel/css/owl.carousel.min.css" />
        <link rel="stylesheet" href="assets/vendors/cleenhearts-icons/style.css" />

        <link rel="stylesheet" href="assets/css/cleenhearts.css" />

        <script src="assets/vendors/wow/wow.js"></script>

        <script src="assets/vendors/wnumb/wNumb.min.js"></script>

        <script src="assets/vendors/jquery/jquery-3.7.0.min.js"></script>
        <script src="assets/vendors/jarallax/jarallax.min.js"></script>
        <script src="assets/vendors/jquery-ajaxchimp/jquery.ajaxchimp.min.js"></script>
        <script src="assets/vendors/jquery-magnific-popup/jquery.magnific-popup.min.js"></script>
        <script src="assets/vendors/swiper/js/swiper-bundle.min.js"></script>
        <script src="assets/vendors/owl-carousel/js/owl.carousel.min.js"></script>

        <script async src="assets/js/cleenhearts.js"></script>
      </Head>
      {/* <HomePage /> */}
      <div dangerouslySetInnerHTML={{ __html: HomePageContent }} />
      {/* <FrameWrapper>
        <iframe src="https://truerep.github.io/fundsdome-ui" width="100%" height="100%" frameborder="0"></iframe>
      </FrameWrapper> */}
    </>
  )
}

const FrameWrapper = styled.div`
  height: calc(100vh - 4px);
  width: 100vw;
`;
