import { HomePage } from '@/components';
import Head from 'next/head'
import styled from 'styled-components'

export default function Home() {
  return (
    <>
      <Head>
        <title>FundsDome</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <HomePage /> */}
      <FrameWrapper>
            <iframe src="https://truerep.github.io/fundsdome-ui" width="100%" height="100%" frameborder="0"></iframe>
          </FrameWrapper>
    </>
  )
}

const FrameWrapper = styled.div`
  height: calc(100vh - 4px);
  width: 100vw;
`;
